### ISSUE TITLE
Using with Handlebars.js?

### ISSUE THREAD

**Issue by ojtibi** [electblake/CakePHP-Mustache-Plugin#1]
Cool plugin. By the way, I'm just curious if you're using the same templates for front-end view generation using Handlebars? How do you do it?

**Comment by electblake** [comment]
I don't believe I am (in these projects) but I've had issues in the past (as you can't define templates with templates) heh.

Generally speaking, you should compile your templates and pass them to the client (manually) although, depends on implementation/framework etc.

**Comment by ojtibi** [comment]
Interesting, I guess it might be a good idea to create a separate "static" view (or even just a plain file) to push to the client. Thanks for the reply. :+1:
